name: Build Brave Portable (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install -y visualstudio2019buildtools python nodejs-lts
          refreshenv
          npm install -g npm@latest
          npm install -g n
          n 20.8.0

      - name: Clone Depot Tools (Shallow Clone)
        run: |
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add Depot Tools to Path
        run: |
          echo "$GITHUB_WORKSPACE/depot_tools" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
          echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

      - name: Verify Depot Tools Installation
        run: |
          cd depot_tools
          gclient --version

      - name: Clone Brave Repo (Shallow Clone)
        run: |
          git clone --depth=1 https://github.com/brave/brave-browser.git
          cd brave-browser

      - name: Set Up Chromium Environment
        run: |
          cd brave-browser
          npm install
          gclient sync --no-history

      - name: Configure Portable Build
        run: |
          cd brave-browser
          gn gen out/Release --args="is_official_build=true is_debug=false"

      - name: Build Brave
        run: |
          cd brave-browser
          ninja -C out/Release chrome

      - name: Create Portable Directory
        run: |
          mkdir BravePortable
          cp -r brave-browser/out/Release/* BravePortable/

      - name: Modify Brave for Full Portability
        run: |
          echo 'UserData=.\UserData' > BravePortable/brave-portable.ini

      - name: Package Brave Portable (ZIP)
        run: |
          Compress-Archive -Path BravePortable -DestinationPath BravePortable.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Brave-Portable-Windows
          path: BravePortable.zip

      - name: Post Checkout Code
        run: echo "Build completed!"
